accounts/urls.py
from django.conf.urls import url

from accounts import views

app_name = "accounts"
urlpatterns = [
    url(r"^signup$", views.signup_user, name = "signup"),
    url(r"^login$", views.login_user, name = "login"),
    url(r"^logout$", views.logout_user, name = "logout"),
    url(r"^user/prefs/load$", views.load_prefs, name = "load_prefs"),
    url(r"^user/prefs/update$", views.update_prefs, name = "update_prefs"),
    url(r"^user/prefs/remove$", views.remove_prefs, name = "remove_prefs"),
    url(r"^profile$", views.profile, name = "profile"),
    url(r"^prefs$", views.prefs, name = "prefs"),
    url(r"^watchlist$", views.watchlist, name = "watchlist"),
    url(r"^watchlist/add$", views.watchlist_add, name= "watchlist_add"),
    url(r"^watchlist/remove$", views.watchlist_remove, name = "watchlist_remove"),
    url(r"^recos$", views.recos, name = "recos"),
    url(r"^reco/(\d+)/$", views.reco, name = "reco"),
    url(r"^reco/(\d+)/title$", views.reco_title, name = "reco_title"),
    url(r"^password$", views.password, name = "password"),
    url(r"^delete$", views.delete, name = "delete"),
]

tmdb/urls.py
from django.conf.urls import url, include

from . import views


app_name = "movies"
urlpatterns = [
    url(r"^popular$", views.popular_movies, name="popular_movies"),
    url(r"^search$", views.search_movies, name="search_movies"),
    url(r"^nowplaying$", views.nowplaying_movies, name="nowplaying_movies"),
    url(r"^upcoming$", views.upcoming_movies, name="upcoming_movies"),
    url(r"^toprated$", views.toprated_movies, name="toprated_movies"),
    url(r"^(\d+)/info$", views.movie_info, name="movie_info"),
]

w2w/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r"", include("main.urls")),
    url(r"^movies/", include("tmdb.urls", namespace="movies")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import (
    AbstractBaseUser, BaseUserManager
)
from django.conf import settings
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save

from tmdb.models import Movie


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_real = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    mean_rating = models.FloatField(default=0)

    def add_pref(self, id, rating = 10, timestamp = None, 
        save = True, update_mean = True
    ):
        new_pref = self.pref.add(id, rating, timestamp)
        if update_mean:
            self.update_mean_rating(False)
        if save:
            self.save()
        return new_pref


    def add_to_watchlist(self, id):
        return self.watchlist.add(id) # None ?


    def remove_from_watchlist(self, id):
        return self.watchlist.remove(id)


    def get_pref(self, id):
        return self.pref.data.get(movie__id=id)


    def remove_pref(self, id):
        return self.pref.remove(id)


    def update_mean_rating(self, save = True):
        ratings = self.pref.data.values("rating").all()
        self.mean_rating = sum(item["rating"] for item in ratings)/len(ratings)      
        if save:
            self.save()


    def update_profile(self, data):
        self.email = data.get("email", self.email)
        self.save()
        self.profile.update(data)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, **kwargs):
    # Create associated profile
    try:
        UserProfile.objects.get(user=instance)
    except UserProfile.DoesNotExist:
        UserProfile.objects.create(user=instance)

    # Create associated preferences list
    try:
        PrefList.objects.get(user=instance)
    except PrefList.DoesNotExist:
        PrefList.objects.create(user=instance)

    # Create associated watchlist
    try:
        WatchList.objects.get(user=instance)
    except WatchList.DoesNotExist:
        WatchList.objects.create(user=instance)


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = "profile",
        blank = False,
        null = False
    )

    MALE = "M"
    FEMALE = "F"
    SEX = ((MALE, "Male"),(FEMALE, "Female"))  

    birthday = models.DateTimeField(blank = True, null = True)
    country = models.CharField(blank = True, null = True, max_length = 255)
    sex = models.CharField(blank = True, null = True, max_length = 1, 
        choices=SEX)

    def update(self, data):
        self.country = data.get("country", self.country)
        self.sex = data.get("sex", self.sex)
        self.birthday = data.get("birthday", self.birthday)
        self.save()


class PrefList(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = "pref",
        blank = True,
        null = True
    )

    # models.ForeignKey(settings.AUTH_USER_MODEL, related_name = "pref")
    movies = models.ManyToManyField(Movie, through = "MoviePref",
        related_name = "preflist")

    def add(self, id, rating = 10, timestamp = None, save = True):
        try:
            movie = Movie.objects.get(id = id)
        except Movie.DoesNotExist:
            return None
        timestamp = timestamp if timestamp else timezone.now()

        try: # update preferences 
            pref_movie = MoviePref.objects.get(preflist = self, movie = movie)
            pref_movie.rating = rating
            pref_movie.timestamp = timestamp
        except MoviePref.DoesNotExist: # new preferences
            pref_movie = MoviePref(
                preflist = self,
                movie = movie,
                rating = rating,
                timestamp = timestamp
            )
        if save:
            pref_movie.save()
        return pref_movie


    def remove(self, id):
        try:
            pref_movie = MoviePref.objects.get(preflist = self, movie__id = id)
            pref_movie.delete()
            return 1
        except MoviePref.DoesNotExist:
            return 0

        
class MoviePref(models.Model):
    preflist = models.ForeignKey(PrefList, related_name = "data")
    movie = models.ForeignKey(Movie, related_name = "ratings")
    rating = models.FloatField()
    timestamp = models.DateTimeField(default = timezone.now)


class WatchList(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = "watchlist",
        blank = False,
        null = False
    )

    # Do not create related objects in Movie
    movies = models.ManyToManyField(Movie, related_name = "+")

    def add(self, id):
        movie = Movie.objects.get(id = id)
        self.movies.add(movie)

    def remove(self, id):
        try:
            self.movies.get(id = id).delete()
            return 1
        except Movie.DoesNotExist:
            return 0

reco/models.py
from tmdb.models import Movie

from django.db import models
from django.utils import timezone
from django.conf import settings
from reco.exceptions import SimCalculationError
from django.shortcuts import reverse


class Reco(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank = True, 
        null = True, related_name = "recos")

    timestamp = models.DateTimeField(default = timezone.now)
    title = models.TextField(blank = True, null = True)

    def get_absolute_url(self):
        return reverse("accounts:reco", args=[self.id])

    @staticmethod
    def create_new(base, reco, user = None, title = None):
        reco_ = Reco.objects.create(title = title)

        obj2save = list()
        for item in base:
            base2reco = RecoBase(reco = reco_, rating = item["rating"])
            base2reco.movie_id = item["id"]
            obj2save.append(base2reco)
        RecoBase.objects.bulk_create(obj2save)

        obj2save = list()
        for item in reco:
            movie2reco = RecoMovie(reco = reco_, score = None)
            movie2reco.movie_id = item["id"]
            obj2save.append(movie2reco)
        RecoMovie.objects.bulk_create(obj2save)

        if user and user.is_authenticated():
            user.recos.add(reco_)

        return reco_


class RecoBase(models.Model):
    reco = models.ForeignKey(Reco, related_name = "base")
    movie = models.ForeignKey(Movie, related_name = "+")
    rating = models.IntegerField()


class RecoMovie(models.Model):
    reco = models.ForeignKey(Reco, related_name = "movies")
    movie = models.ForeignKey(Movie, related_name = "+")
    score = models.FloatField(blank=True,null=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate, get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Page, Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import update_session_auth_hash
from django.template import Context
from django.template.loader import get_template

import w2w.settings
from accounts.forms import (
    SignUpForm, LoginForm, INVALID_LOGIN_ERROR, EditProfileForm,
    ChangePasswordForm, DeleteAccountForm
)
from tmdb.models import Movie
from reco.models import Reco

User = get_user_model()


def signup_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.backend = w2w.settings.AUTHENTICATION_BACKENDS[0]
            login(request, user)
            return redirect("/")
    else:
        form = SignUpForm()
        
    return render(request, "accounts/signup.html", {"form": form})


def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(email = email, password = password)
            if user is not None:
                user.backend = w2w.settings.AUTHENTICATION_BACKENDS[0]
                login(request, user)
                return redirect("/")
            else:
                form.add_error(field = None, error = INVALID_LOGIN_ERROR)
    else:
        form = LoginForm()

    return render(request, "accounts/login.html", {"form": form})


@login_required
def logout_user(request):
    logout(request)
    return redirect("/")


@login_required
@csrf_exempt
def load_prefs(request):
    prefs = list(request.user.pref.data.order_by("timestamp").
        values("movie__id", "movie__title", "rating").
        annotate(id=F("movie__id"),title=F("movie__title")).
        values("id", "title", "rating").all())
    return JsonResponse({"status": "OK", "prefs": prefs}, safe=False)


@login_required
@csrf_exempt
def update_prefs(request):
    try:
        movie_id = request.POST["id"]
        movie_rating = request.POST["rating"]
        request.user.add_pref(id = movie_id, rating = movie_rating)
        return JsonResponse({"status": "OK"}, safe=False)
    except KeyError:
        return JsonResponse({"status": "ERROR"}, safe=False)


@login_required
@csrf_exempt
def remove_prefs(request):
    try:
        movie_id = request.POST["id"]
        removed = request.user.remove_pref(movie_id)
        return JsonResponse({"status": "OK", "removed": removed}, safe=False)
    except KeyError:
        return JsonResponse({"status": "ERROR"}, safe=False)
    

@login_required
def profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.user, request.POST)
        if form.is_valid():     
            request.user.update_profile(form.cleaned_data)
            return redirect(reverse("accounts:profile"))
    else:
        form = EditProfileForm(request.user)
    return render(request, "accounts/profile.html", 
        {"form": form, "form_delete": form}
    )


@login_required
def prefs(request):
    page = request.GET.get("page", 1)
    page_size = request.GET.get("page_size", 10)

    prefs_db = list(request.user.pref.data.order_by("timestamp").
        values("movie__id", "movie__title", "rating").
        annotate(id=F("movie__id"),title=F("movie__title")).
        values("id", "title", "rating").all())
    paginator = Paginator(prefs_db, page_size)

    try:
        prefs = paginator.page(page)
    except PageNotAnInteger:
        prefs = paginator.page(1)
    except EmptyPage:
        prefs = paginator.page(paginator.num_pages)

    return render(request, "accounts/prefs.html", { "prefs": prefs})


@login_required
def watchlist(request):
    page = request.GET.get("page", 1)
    page_size = request.GET.get("page_size", 10)

    watchlist_db = list(request.user.watchlist.movies.order_by("title").
        values("id", "title").all())
    paginator = Paginator(watchlist_db, page_size)

    try:
        watchlist = paginator.page(page)
    except PageNotAnInteger:
        watchlist = paginator.page(1)
    except EmptyPage:
        watchlist = paginator.page(paginator.num_pages)
    
    return render(request, "accounts/watchlist.html", {"watchlist": watchlist})


@login_required
@csrf_exempt
def watchlist_add(request):
    try:
        movie_id = request.POST["id"]
    except KeyError:
        return JsonResponse({"status": "ERROR", "msg": "No movie id."}, 
            safe=False)

    try:
        request.user.add_to_watchlist(id = movie_id)
    except Movie.DoesNotExist:
        return JsonResponse({"status": "ERROR", "msg": "Invalid movie id"}, 
            safe=False)

    return JsonResponse({"status": "OK"}, safe=False)


@login_required
@csrf_exempt
def watchlist_remove(request):
    try:
        movie_id = request.POST["id"]
    except KeyError:
        return JsonResponse({"status": "ERROR", "msg": "No movie id."}, 
            safe=False)
    request.user.watchlist.movies.filter(id=movie_id).delete()
    return JsonResponse({"status": "OK"}, safe=False)


@login_required
def recos(request):
    page = request.GET.get("page", 1)
    page_size = request.GET.get("page_size", 10)

    recos_db = request.user.recos.order_by("-timestamp").all()
    paginator = Paginator(recos_db, page_size)

    try:
        recos = paginator.page(page)
    except PageNotAnInteger:
        recos = paginator.page(1)
    except EmptyPage:
        recos = paginator.page(paginator.num_pages)

    return render(request, "accounts/recos.html", {"recos": recos})


@login_required
def reco(request, id):
    try:
        reco = Reco.objects.get(id=id, user=request.user)
    except Reco.DoesNotExist:
        return redirect(reverse("accounts:recos"))
    return render(request, "accounts/reco.html", {"reco": reco})


@login_required
@csrf_exempt
def reco_title(request, id):
    try:
        title = request.POST["title"]
    except:
        return JsonResponse({"status": "ERROR", "msg": "No title"}, safe=False)

    try:
        reco = Reco.objects.get(id=id,user=request.user)
    except:
        return JsonResponse({"status": "ERROR", "msg": "No reco"}, safe=False)

    reco.title = title
    reco.save()
    return JsonResponse({"status": "OK"}, safe=False)


@login_required
def password(request):
    password_changed = False
    if request.method == "POST":
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            request.user.set_password(form.cleaned_data["new_password"])
            request.user.save()
            update_session_auth_hash(request, request.user)
            password_changed = True
    else:
        form = ChangePasswordForm(request.user)
    return render(request, "accounts/password.html", 
        {"form": form, "password_changed": password_changed})


@login_required
def delete(request):
    if request.method == "POST":
        form = DeleteAccountForm(request.user, request.POST)
        if form.is_valid():
            request.user.delete()
            return redirect(reverse("home"))
    else:
        form = DeleteAccountForm(request.user)
    return render(request, "accounts/delete.html", {"form": form})

accounts/templates/accounts/delete.html
{% extends 'accounts/profile_base.html' %}
{% load static %}

{% block title %}{{ block.super }}Delete Account{% endblock title %}

{% block delete_active %}submenu-active{% endblock %}

{% block body %}
{{ block.super }}
<div class="container container-w2w">
     <div class="page-header">
        <h3>Delete Account</h3>
    </div>
    {% if form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <div class="alert alert-danger" role="alert">Caution! This operation is not reversible.</div>
    <p>You need to verify your person with valid password in order to delete this account.</p>
    <form method="POST" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password|linebreaks }}
            {% if form.errors %}
                <div class="has-error">
                    <div class="help-block">{{ form.password.errors }}</div>
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <input type="submit" id="id_submit" class="btn btn-danger" value="Delete Account"/>
        </div>
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Log In{% endblock title %}

{% block styles %}
{{ block.super }}
<style>
    .container-w2w {
        width: 300px !important;
    }
    input {
        display: block;
        width: 100%;
    }
</style>
{% endblock styles %}

{% block body %}
<div class="container container-w2w">
    <div class = "page-header">
        <h2>Login</h2>
    </div>
    <form method="POST" role="form">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            {{ form.email|linebreaks }}
            {% if form.errors %}
                <div class="has-error">
                    <div class="help-block">{{ form.email.errors }}</div>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password|linebreaks }}
            {% if form.errors %}
                <div class="has-error">
                    <div class="help-block">{{ form.password.errors }}</div>
                </div>
            {% endif %}
        </div>

        <div class="has-error">
            <div class="help-block">{{ form.non_field_errors }}</div>
        </div>

        <div class="form-group">
            <input type="submit" id="id_submit" class="btn btn-primary" 
                   value="Submit"/>
        </div>

    </form>
</div>
{% endblock body %}

accounts/templates/accounts/password.html
{% extends 'accounts/profile_base.html' %}
{% load static %}

{% block title %}{{ block.super }}Change Password{% endblock title %}

{% block password_active %}submenu-active{% endblock %}

{% block body %}
{{ block.super }}
<div class="container container-w2w">
    <div class="page-header">
        <h3>Change Password</h3>
    </div>
    {% if password_changed %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            Your password has been successfuly changed.
        </div>
    {% endif %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <form method="POST" role="form" class="form-horizontal">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.password.id_for_label }}" class="col-sm-3 control-label">Current Password</label>
            <div class="col-sm-9">
                {{ form.password|linebreaks }} 
                {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.password.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.new_password.id_for_label }}" class="col-sm-3 control-label">New Password</label>
            <div class="col-sm-9">
               {{ form.new_password|linebreaks }}
               {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.new_password.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.new_password2.id_for_label }}" class="col-sm-3 control-label">Confirm New Passsword</label>
            <div class="col-sm-9">
               {{ form.new_password2|linebreaks }}
               {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.new_password2.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <input type="submit" id="id_submit" class="btn btn-primary" 
                       value="Change Password"/>
            </div>
        </div>
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/profile.html
{% extends 'accounts/profile_base.html' %}
{% load static %}

{% block title %}{{ block.super }}Edit{% endblock title %}

{% block edit_active %}submenu-active{% endblock %}

{% block styles %}
{{ block.super }}
<link href="{% static 'css/jquery.datetimepicker.min.css' %}" rel="stylesheet">
{% endblock styles %}

{% block body %}
{{ block.super }}
<div class="container container-w2w">

    <div class="page-header">
        <h3>Profile Information</h3>
        Your personal information can be used by our system to improve your recommendations.
    </div>

    <form method="POST" role="form" class="form-horizontal">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.email.id_for_label }}" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                {{ form.email|linebreaks }} 
                {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.email.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.birthday.id_for_label }}" class="col-sm-2 control-label">Birthday</label>
            <div class="col-sm-10">
               {{ form.birthday|linebreaks }}
               {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.birthday.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.sex.id_for_label }}" class="col-sm-2 control-label">Sex</label>
            <div class="col-sm-10">
               {{ form.sex|linebreaks }}
               {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.sex.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.country.id_for_label }}" class="col-sm-2 control-label">Country</label>
            <div class="col-sm-10">
               {{ form.country|linebreaks }}
               {% if form.errors %}
                    <div class="has-error">
                        <div class="help-block">{{ form.country.errors }}</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" id="id_submit" class="btn btn-primary" 
                       value="Save Changes"/>
            </div>
        </div>
    </form>
</div>
{% endblock body %}

{% block body_scripts %}
{{ block.super }}
<script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    $.datetimepicker.setLocale('en');
    $('#id_birthday').datetimepicker({
        timepicker:false,
        format:'Y-m-d'
    });
</script>
{% endblock %}

accounts/templates/accounts/profile_base.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ block.super }}Profile - {% endblock title %}

{% block styles %}
{{ block.super }}
    <link href="{% static 'css/w2w.accounts.css' %}" rel="stylesheet">
{% endblock styles %}

{% block body %}
<div class="container container-navbar">
    <ul class="side-navbar">
      <li><a class="{% block edit_active %}{% endblock %}" 
             href="{% url 'accounts:profile' %}">Edit</a></li>
      <li><a class="{% block prefs_active %}{% endblock %}" 
             href="{% url 'accounts:prefs' %}">Preferences</a></li>
      <li><a class="{% block watchlist_active %}{% endblock %}"
             href="{% url 'accounts:watchlist' %}">Watchlist</a></li>
      <li><a class="{% block recos_active %}{% endblock %}"
             href="{% url 'accounts:recos' %}">Recommendations</a></li>
      <li><a class="{% block password_active %}{% endblock %}"
             href="{% url 'accounts:password' %}">Change Password</a></li>
      <li><a class="{% block delete_active %}{% endblock %}"
             href="{% url 'accounts:delete' %}">Delete Account</a></li>
    </ul>
</div>
{% endblock body %}

{% block navbar_profile %}
    <li><a href="{% url 'accounts:profile' %}">Edit</a></li>
    <li><a href="{% url 'accounts:prefs' %}">Preferences</a></li>
    <li><a href="{% url 'accounts:watchlist' %}">Watchlist</a></li>
    <li><a href="{% url 'accounts:recos' %}">Recommendations</a></li>
    <li><a href="{% url 'accounts:password' %}">Change Password</a></li>
    <li><a href="{% url 'accounts:delete' %}">Delete Account</a></li>
{% endblock %}

accounts/templates/accounts/recos.html
{% extends 'accounts/profile_base.html' %}
{% load static %}

{% block title %}{{ block.super }}Recommendations{% endblock title %}

{% block recos_active %}submenu-active{% endblock %}

{% block styles %}
{{ block.super }}
<style>
    #reco-list {
        display: table;
        table-layout: fixed;
        width: 100%;
        border-collapse: collapse;
    }
    .reco-movie {
        display: table-row;
        width: 100%;
        margin: 20px;
        border-bottom: 1px solid black;
        padding: 100px;
        height: 0px;
    }
    .reco-movie-title {
        display: table-cell;
        word-wrap: break-word;
        vertical-align: middle;
        padding: 15px 5px;
        height: 100%;
        text-align: left;
        width: 50%;

        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>
{% endblock %}

{% block body %}
{{ block.super }}
<div class = "container-w2w">
    <div class="page-header">
        <h3>Your Recommendations</h3>
    </div>
    {% if recos.paginator.count == 0 %}
        It seems you have not yet get any recommendations. What are you waiting for? Please visit recommendation section and find out new movies. 
    {% else %}
        <div id="reco-list">
            {% for reco in recos %}
                <div class="reco-movie" data-movie-id="{{ reco.id }}">
                    <span class='reco-movie-title'>
                        <a href="{{ reco.get_absolute_url }}">
                        {% if reco.title %}
                            No Title
                        {% else %}
                            {{ reco.title }} 
                        {% endif %}
                        </a>
                        ({{ reco.timestamp|date:'Y-m-d H:i' }})
                    </span>
                </div>
            {% endfor %}
        </div>

        {% if recos.has_other_pages %}
            <ul class="pagination">
                {% if recos.has_previous %}
                    <li><a href="?page={{ recos.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in recos.paginator.page_range %}
                    {% if recos.number == i %}
                        <li class="active">
                            <span>{{ i }} <span class="sr-only">(current)</span></span>
                        </li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if recos.has_next %}
                    <li><a href="?page={{ recos.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    {% endif %}
</div>
{% endblock %}