accounts/urls.py
from django.conf.urls import url

from accounts import views

app_name = "accounts"
urlpatterns = [
    url(r"^signup$", views.signup_user, name = "signup"),
    url(r"^login$", views.login_user, name = "login"),
    url(r"^logout$", views.logout_user, name = "logout"),
    url(r"^user/prefs/load$", views.load_prefs, name = "load_prefs"),
    url(r"^user/prefs/update$", views.update_prefs, name = "update_prefs"),
    url(r"^user/prefs/remove$", views.remove_prefs, name = "remove_prefs"),
    url(r"^profile$", views.profile, name = "profile"),
    url(r"^prefs$", views.prefs, name = "prefs"),
    url(r"^watchlist$", views.watchlist, name = "watchlist"),
    url(r"^watchlist/add$", views.watchlist_add, name= "watchlist_add"),
    url(r"^watchlist/remove$", views.watchlist_remove, name = "watchlist_remove"),
    url(r"^recos$", views.recos, name = "recos"),
    url(r"^reco/(\d+)/$", views.reco, name = "reco"),
    url(r"^reco/(\d+)/title$", views.reco_title, name = "reco_title"),
    url(r"^password$", views.password, name = "password"),
    url(r"^delete$", views.delete, name = "delete"),
]

main/urls.py
from django.conf.urls import url

from main.views import home_page, reco_page, make_reco, about_page

urlpatterns = [
    url(r"^$", home_page, name = "home"),
    url(r"^about$", about_page, name = "about"),
    url(r"^reco", reco_page, name = "reco"),
    url(r"^make_reco", make_reco, name = "make_reco")
]

tmdb/urls.py
from django.conf.urls import url, include

from . import views


app_name = "movies"
urlpatterns = [
    url(r"^popular$", views.popular_movies, name="popular_movies"),
    url(r"^search$", views.search_movies, name="search_movies"),
    url(r"^nowplaying$", views.nowplaying_movies, name="nowplaying_movies"),
    url(r"^upcoming$", views.upcoming_movies, name="upcoming_movies"),
    url(r"^toprated$", views.toprated_movies, name="toprated_movies"),
    url(r"^(\d+)/info$", views.movie_info, name="movie_info"),
]

w2w/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r"", include("main.urls")),
    url(r"^movies/", include("tmdb.urls", namespace="movies")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
]

reco/models.py
from tmdb.models import Movie

from django.db import models
from django.utils import timezone
from django.conf import settings
from reco.exceptions import SimCalculationError
from django.shortcuts import reverse


class Reco(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank = True, 
        null = True, related_name = "recos")

    timestamp = models.DateTimeField(default = timezone.now)
    title = models.TextField(blank = True, null = True)

    def get_absolute_url(self):
        return reverse("accounts:reco", args=[self.id])

    @staticmethod
    def create_new(base, reco, user = None, title = None):
        reco_ = Reco.objects.create(title = title)

        obj2save = list()
        for item in base:
            base2reco = RecoBase(reco = reco_, rating = item["rating"])
            base2reco.movie_id = item["id"]
            obj2save.append(base2reco)
        RecoBase.objects.bulk_create(obj2save)

        obj2save = list()
        for item in reco:
            movie2reco = RecoMovie(reco = reco_, score = None)
            movie2reco.movie_id = item["id"]
            obj2save.append(movie2reco)
        RecoMovie.objects.bulk_create(obj2save)

        if user and user.is_authenticated():
            user.recos.add(reco_)

        return reco_


class RecoBase(models.Model):
    reco = models.ForeignKey(Reco, related_name = "base")
    movie = models.ForeignKey(Movie, related_name = "+")
    rating = models.IntegerField()


class RecoMovie(models.Model):
    reco = models.ForeignKey(Reco, related_name = "movies")
    movie = models.ForeignKey(Movie, related_name = "+")
    score = models.FloatField(blank=True,null=True)

main/views.py
import json

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F

from reco.source import UserSource, JsonSource
from reco.engine import RecoManager, SlopeOne
from reco.settings import (
    RECO_MAX_MOVIES, RECO_MIN_FREQ, RECO_MIN_RATING
)
from tmdb.models import Movie
from accounts.models import PrefList


def about_page(request):
    return render(request, "main/about.html")

def home_page(request):
    if request.user.is_authenticated():
        reco = request.user.recos.order_by("-timestamp").first()
    else:
        reco = None
    return render(request, "main/home.html", { "reco": reco } )

def reco_page(request):
    reco_type = request.GET.get("type", "standalone")
    if reco_type != "general" and reco_type != "standalone":
        reco_type = "standalone"

    preflist = []
    if reco_type == "general":
        if not request.user.is_authenticated():
            return redirect("/")

        preflist = list(request.user.pref.data.values(
            "movie__id", "movie__title", "rating"
        ).annotate(title=F("movie__title"), id=F("movie__id")).values(
            "id", "title", "rating"
        ).all())

    return render(request, "main/reco.html", {
        "preflist": json.dumps(preflist),
        "reco_type": reco_type
    })  

@csrf_exempt
def make_reco(request):
    reco_request = json.loads(request.body.decode())
    reco_type = reco_request["type"]

    if request.user.is_authenticated() and reco_type == "general":
        source = UserSource(user = request.user)
    else:
        source = JsonSource(data = reco_request["prefs"], user = request.user)

    # Save pseudo preflist for anonymouse users. They can improve
    # recommendations for other users.
    if not request.user.is_authenticated():
        preflist = PrefList.objects.create()
        for movie in source.get_data():
            preflist.add(movie["id"], movie["rating"])

    rengine = RecoManager(source = source, engine = SlopeOne())
    reco = rengine.make_reco()

    if len(reco) > 0:
        reco_final = [ movie for movie in reco if movie["rating"] > RECO_MIN_RATING and
             movie["freq"] > RECO_MIN_FREQ ]
        reco_final = sorted(reco_final, key=lambda x: x["rating"], 
            reverse = True)
        reco_final = reco_final[0:min(len(reco_final), RECO_MAX_MOVIES)]

        reco_ids = [ movie["id"] for movie in reco_final ]
        movies = list(Movie.objects.values("id", "title")\
            .filter(id__in = reco_ids))
        movies = { movie["id"]: movie["title"] for movie in movies }

        for movie in reco_final:
            movie["title"] = movies.get(movie["id"])
            del movie["freq"]
    else:
        reco_final = []

    # substitute orginal reco with preparated by this view
    reco_db = rengine.save_reco(
        reco = reco_final
    ) 

    return JsonResponse({"status": "OK", "movies": reco_final, "id": 
        reco_db.id, "title": reco_db.title}, safe=False)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{block.super}} About{% endblock title %}

{% block styles %}
{{ block.super }}
<style>
    p {
        text-align: justify;
    }
    #tmdb-logo {
        margin: 10px;
        width: 300px;
    }
</style>
{% endblock %}

{% block body %}
{{ block.super }}
{% include 'main/movieinfo.html' %}
<div class="container container-w2w">
    <div class="page-header" id="sx-device-header">
        <h2>"<strong>W2W</strong>" - <strong>What To Watch</strong></h2>
    </div>

    <p>What To Watch (W2W) is a web-based application providing movies
    recommendation on the base of the users preferences. It's just the first 
    installment of the app so we ask for a little bit of understanding. If you
    have any questions, remarks or you found a bug, please give us notice by
    <a href="mailto:hakubaa@gmail.com">e-mail.</a>
    </p>

    <p>The recommendations are made on the base of item-based collaborative 
    filtering. To put is simple, when we prepare a recommendation for a user,
    we take into consideration the preferences of other users. Collaborative
    filtering algorithms are widly used in many domains and provide significant 
    improvement in comparison with other methods. For the present moment,
    algorithm that is used by W2W is SlopeOne. Despite its simplicity, it is
    comparable to more complicated and computationally expensive algorithms. 
    You can find more information about this algorithm on 
    <a href="https://en.wikipedia.org/wiki/Slope_One">Wikipedia</a>.</p>

    <h4>Functionalities</h4>
    <p>
    W2W provieds movies recommendation. In order to receive a recommendation a 
    user has to explicitly state her/his preferences by grading selected movies 
    on five points scale (1-5). There are two modes:
    <ul>
    <li>Stand-Alone Search</li>
    <li>General Search</li>
    </ul>
    </p>
    <p>
    <strong>Stand-Alone Search</strong> was primarily designed for new and not 
    authenticated users. However logged in users can also take adventage of this
    mode. You have to state your preferences from the very beginning every time
    you want a recommendation. It can be a little bit burdensome when one 
    frequently makes use of W2W. That is why <strong>General Search</strong> 
    mode was introduced.</p>

    <p><strong>General Search</strong> mode is intended only for signed up users. 
    We remember your preferences, which you can adjust any time, and we prepare 
    comprehensive recommendation on the base of all your preferences. You can 
    create list of movies you want to watch - watchlist. You can also visits your 
    past recommendations. Of-course if you would like receive new recommendation 
    not related to your overall preferences, you can always choose Stand-Alone 
    Search.</p>

    <p>We would like to fully appreciate <a href="https://www.themoviedb.org">TMDB</a> 
    for providing data used by W2W. Thank You Very Much.</p>

    <a href="https://www.themoviedb.org">
    <img id="tmdb-logo" src="https://www.themoviedb.org/assets/bb45549239e25f1770d5f76727bcd7c0/images/v4/logos/408x161-powered-by-rectangle-blue.png">
    </a>

    <p>So explore a little. Search for your favorite movies. Build a list of movies 
    you want to watch. We're really proud of the service we've built and hope 
    you find it as useful.</p>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>W2W - {% block title %}{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/w2w.base.css' %}" rel="stylesheet">
    {% block styles %}{% endblock styles %}
</head>

<body>
    {% block navbar %}
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">W2W</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" role="button"
                               data-toggle="dropdown" aria-haspopup="true" 
                               aria-expanded="false"
                            >{{user.email}}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% block navbar_profile %}
                                    <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                                {% endblock %}
                                <li role="separator" class="divider"></li>
                                <li><a id="id_logout" href="{% url 'accounts:logout' %}">Log Out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a id="id_signup" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        <li><a id="id_login" href="{% url 'accounts:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block body %}{% endblock %}  
    <footer class="footer-w2w">
        <div class="container">
            <p class="text-muted">&copy; 2016 <a href="mailto:hakubaa@gmail.com">JAGO</a>
            ALL RIGHTS RESERVED
            </p>
        </div>
    </footer>

    <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block body_scripts %}{% endblock %}
</body>

</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}What To Watch{% endblock title %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/w2w.home.css' %}">
<link rel="stylesheet" href="{% static 'css/w2w.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/w2w.movieinfo.css' %}">
<link rel="stylesheet" href="{% static 'css/w2w.prefs.css' %}">
{% endblock styles %}

{% block body %}
{{ block.super }}
{% include 'main/movieinfo.html' %}
<div class="container container-w2w">
    <div class="page-header" id="lg-device-header">
        <h1>Welcome to "<strong>W2W</strong>" - <strong>What To Watch</strong>
        <br><small>Looking for some new movies to watch? - You've found the right place!</small>
        </h1>
    </div>
    <div class="page-header" id="sx-device-header">
        <h2>"<strong>W2W</strong>" - <strong>What To Watch</strong></h2>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Stand-Alone Search</h3>
                    <p>
                        <strong>Quick</strong>, <strong>one-time</strong> search for 
                        <strong>anonymous</strong> as well as for <strong>authenitcated users</strong>.
                        State your preferences and we recommend you some movies worth to watch.
                    </p>
                    <a href="{% url 'reco' %}?type=standalone" class="btn btn-sx btn-default" 
                          id="standalone-reco-btn" role="button">Begin Stand-Alone Search</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="thumbnail">
                <div class="caption">
                    <h3>General Search</h3>
                    <p><strong>Complex</strong> and <strong>general</strong> search for
                    <strong>authenticated users</strong>. State and adjust your preferences, add new movies to
                    your watchlist or view your previous recommendations.</p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'reco' %}?type=general" class="btn btn-sx btn-default" 
                           id="general-reco-btn" role="button">Begin General Search</a>
                    {% else %}
                        <p>Please <a id="id_signup" href="{% url 'accounts:signup' %}" 
                           style="color: white !important;"><strong>Sign Up</strong></a> or 
                        <a id="id_login" href="{% url 'accounts:login' %}"
                           style="color: white !important;"><strong>Log In</strong></a> 
                        into your account to take adventage of general search mode.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% if reco %}
    <div class = "container-w2w">
        <div class = "page-header">
            <h3>
                Your Last Recommendation<br>
                <small>
                {% if reco.title %}
                    No Title
                {% else %}
                    {{ reco.title }}
                {% endif %}
                ({{ reco.timestamp|date:'Y-m-d H:i' }})</small>
            </h3>
        </div>
        <h4>Recommended Movies</h4>
        {% if reco.movies.count == 0 %}
            It seems there were no movies recommended to you.
        {% else %}
            <div class="reco-list active">
            {% for movie in reco.movies.all %}
                <div class="pref-movie">
                    <span class="pref-movie-title">
                        <a href='#movieInfo' data-toggle='modal' data-movie-id="{{movie.movie.id}}">
                            {{movie.movie.title}}
                        </a>
                        (<a href="#" data-movie-id="{{movie.movie.id}}" 
                            class="pref-add-to-watchlist">+Watchlist</a>)
                    </span>
                </div>
                {% if forloop.counter|divisibleby:"5" %}
                    {% if not forloop.last %}
                        </div>
                        <div class="reco-list">
                    {% endif %}
                {% endif %}
            {% endfor %}
            </div>
            <dev>
                <button id="reco-list-prev" class="btn btn-default" 
                    type="button">Prev</button>
                <button id="reco-list-next" class="btn btn-default" 
                    type="button">Next</button>
            </dev>
        {% endif %}
    </div>
{% endif %}

<div class="container container-w2w container-with-carousel">
    <div class="page-header">
        <h3>Movies Browser</h3>
    </div>

    <div class="movies-list-ui">
        <div class="btn-group" role="group" aria-label="...">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default dropdown-toggle" 
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Browsing Mode
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a id="popular-browse-mode" href="#">Popular Movies</a></li>
                    <li><a id="toprated-browse-mode" href="#">Top Rated Movies</a></li>
                    <li><a id="upcoming-browse-mode" href="#">Upcoming Movies</a></li>
                    <li><a id="nowplaying-browse-mode" href="#">Now Playing Movies</a></li>
                </ul>
            </div>

            <button class="btn btn-default owl-prev" type="button">&#9666</button>
            <button class="btn btn-default owl-next" type="button">&#9656</button>
        </div>
    </div>

    <div class="alert alert-info alert-dismissible" role="alert" 
         id="movies-list-info">
        <button type="button" class="close" data-dismiss="alert" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span>
        </button>
        <span id="movies-list-info-msg"></span>
    </div>
    <h4 id="browse-mode-name">Popular Movies</h4>
    <div class="owl-carousel"></div>
</div>

<div class="container container-tmdb">
    <a href="https://www.themoviedb.org/">
        <img src="https://www.themoviedb.org/assets/9b3f9c24d9fd5f297ae433eb33d93514/images/v4/logos/408x161-powered-by-rectangle-green.png">
    </a>
</div>
{% endblock %}

{% block body_scripts %}
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
    <script src="{% static 'js/moviesquery.js' %}"></script>
    <script src="{% static 'js/movieshandler.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <script src="{% static 'js/movieinfo.js' %}"></script>
    <script>
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            nav: false, dots: false, loop: false,
            center: false, autoWidth: true, 
            lazyLoad: true, items: 5,
            responsive: {
                0: { items: 1 },
                600: { items: 3 },
                1000: { items: 5 }
            }
        });
        $(".owl-prev").click(function(event) {
            owl.trigger("prev.owl");
        });
        $(".owl-next").click(function(event) {
            owl.trigger("next.owl");
        });
        owl.on('mousewheel', '.owl-stage', function (e) {
            if (e.deltaY>0) {
                owl.trigger('next.owl');
            } else {
                owl.trigger('prev.owl');
            }
            e.preventDefault();
        });
        owl.on('changed.owl.carousel', function(event) {
            if (event.item.index + 20 > event.item.count) {
                if (!MoviesHandler.isEndOfMovies()) {
                    MoviesHandler.getNextPageMovies();
                }
            } 
        });

        // Init MoviesHandler
        MoviesHandler.setMode(new BrowseQuery("/movies/nowplaying"));
        MoviesHandler.noMoreMoviesImg = "{% static 'img/nomoremovies.png' %}";
        MoviesHandler.lackOfPosterImg = "{% static 'img/lackofposter.png' %}";
        MoviesHandler.is_authenticated = {% if user.is_authenticated %}true{%else%}false{%endif%};
        MoviesHandler.getMovies(page = 1);

        function equalHeight(group) {    
            var tallest = 0;    
            group.each(function() {       
                var thisHeight = $(this).height();       
                if(thisHeight > tallest) {          
                    tallest = thisHeight;       
                }    
            });    
            group.each(function() { $(this).height(tallest); });
        } 

        $(document).ready(function() {   
            equalHeight($(".thumbnail")); 
        });

        $("#standalone-reco-btn").click(function() {
            localStorage.setItem("reco-type", "standalone");
        });
        $("#general-reco-btn").click(function() {
            localStorage.setItem("reco-type", "general");
        });

        $("#reco-list-next").click(function() {
            var $current = $(".reco-list.active");
            var $next = $current.next(".reco-list");
            if ($next.length) {
                $current.removeClass("active");
                $next.addClass("active");
            }
        });

        $("#reco-list-prev").click(function() {
            var $current = $(".reco-list.active");
            var $prev = $current.prev(".reco-list");
            if ($prev.length) {
                $current.removeClass("active");
                $prev.addClass("active");
            }
        });
    </script>
{% endblock %}

main/templates/main/movieinfo.html
{% load static %}
<div class="modal fade" id="movieInfo" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" 
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3 id="minfo-title" class="modal-title"></h3>
                <p id="minfo-genres"></p>
                <div id="minfo-add-watchlist" 
                     data-active="{% if user.is_authenticated %}1{%else%}0{% endif %}">
                    <a href="#">+Watchlist</a>
                </div>
            </div>

            <div class="modal-body" id="minfo-loading">
                <img src="{% static 'img/loading.gif' %}">
            </div>

            <div class="modal-body" id="minfo-body">
                <div id="minfo-poster-wrapper">
                    <img id="minfo-poster" src="">
                    <div>
                        <a id="minfo-imdb" href="#" target="_blank">View in IMDB</a><br>
                        <a id="minfo-tmdb" href="#" target="_blank">View in TMDB</a>
                    </div>
                </div>
                <div id="minfo-info-wrapper">
                    <p id="minfo-overview"></p>
                    <dl class="dl">
                        <dt>Runtime (minutes)</dt>
                        <dd id="minfo-runtime"></dd>
                        <dt>Rating (TMDB)</dt>
                        <dd id="minfo-vote"></dd>
                    </dl>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>